### PR TITLE
Fix typo to point to the correct file and add ansible playbook install info

### PR DESCRIPTION
**Pull request by L1ghtn1ng**
Title says it all

Also would be good to have git tag releases https://git-scm.com/book/en/v2/Git-Basics-Tagging

### CODE REVIEW

**Comment by L1ghtn1ng** [comment]
I have also updated the readme and readme install files to point to installing via my ansible playbook

**Comment by webpwnized** [comment]
Thank you for pointing out the typo. As it turns out, there was the same typo on the line above as well, so in that way you found two issues. I did not merge the fix since 1) I needed to fix both mistakes fixed and 2) this merge includes a link to an external repositiory. I do not have bandwidth to monitor external repositories to ensure they are a good fit. However, if you have material you would like to merge into the Mutillidae project itself, I would be able to review the content, consider merges and continue to monitor via the pull request process. Thanks again for pointing out the typo.

**Comment by webpwnized** [comment]
Both of the typos discovered by 	L1ghtn1ng have been corrected in version 2.7.11 which has been pushed.

**Comment by webpwnized** [comment]
On the issue of tagging, I forgot to push my tags that were started over the last couple of releases (after Mutillidae was migrated from SourceForge to GitHub). Thanks L1ghtn1ng for reminding me to push those.

**Pull request closed without merging**
