### PR TITLE
Adding Dockerfile

### PR DESCRIPTION
**Pull request by brosander**
I thought it might be convenient to have a dockerfile for this repo :smile:

### CODE REVIEW

**Comment by webpwnized** [comment]
This is a good idea and a good start. I don't think this Docker includes the LDAP injection functionality. I don't see a reference to an LDAP service or loading of the LDIF file into the directory. Also, it might be interesting to add mutillidae.local into the hosts file. In future versions, setting up an Apache virtual directory with webroot = /var/www/html/mutillidae in Apache so that Mutillidae runs at http://mutillidae.local instead of http://mutillidae.local/mutillidae would be good.

**Comment by brosander** [comment]
@webpwnized fair enough, was just replicating youtube vids as I went :smile: I'll try and remember to submit updates as I mess with it further

**Comment by brosander** [comment]
and ty for merge :smile:

**Comment by msgpeek** [comment]
fyi, there was a merge conflict somewhere along the way: https://github.com/webpwnized/mutillidae/blob/d9228e2e9f1c7d0e4b201ed0a41600fbb1b2f9b2/Dockerfile#L28

**Comment by webpwnized** [comment]
Thanks. I think I fixed it.

**Pull request merged**
